[options]
admin_passwd = $pbkdf2-sha512$600000$996bsxaitHbOOadUCkGIEQ$DIH75Rc/.OE5l4K84VbMrfM1clJo1ZZ2Di2clgx39TOn/Pu5t6Z.SntDTbMtxWsll.AJ5UzXRL3gZUudmV5Cjg
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = odoo/addons,odoo_addons

