# -*- coding: utf-8 -*-
{
    'name': 'Shahtaj Order Booker',
    'version': '19.0.1.0.27',
    'post_init_hook': 'post_init_hook',
    'category': 'Sales',
    'summary': 'Field order booking with routes, visits, GPS, targets, and inventory',
    'depends': ['base', 'contacts', 'sale', 'sale_stock', 'mail', 'account', 'stock'],
    'data': [
        'security/shahtaj_security.xml',
        'security/ir.model.access.csv',
        'security/shahtaj_partner_access.xml',
        'security/shahtaj_partner_access_upgrade.xml',
        'security/shahtaj_record_rules.xml',
        'security/shahtaj_record_rules_fix.xml',
        'security/shahtaj_booker_ui_fix.xml',
        'data/shahtaj_account_data.xml',
        'data/shahtaj_product_data.xml',
        'data/shahtaj_api_data.xml',
        'data/shahtaj_cron.xml',
        'data/shahtaj_accounting_menu_cleanup.xml',
        'data/shahtaj_accounting_action_fix.xml',
        'data/shahtaj_users.xml',
        'views/shahtaj_route_views.xml',
        'views/shahtaj_zone_views.xml',
        'views/shahtaj_partner_views.xml',
        'views/shahtaj_account_payment_views.xml',
        'views/shahtaj_accounting_views.xml',
        'views/shahtaj_accounting_hub_views.xml',
        'views/shahtaj_sale_accounting_views.xml',
        'views/shahtaj_schedule_views.xml',
        'views/shahtaj_visit_task_views.xml',
        'data/shahtaj_visit_action_cleanup.xml',
        'views/shahtaj_visit_views.xml',
        'wizard/shahtaj_visit_checkin_views.xml',
        'views/shahtaj_target_views.xml',
        'views/shahtaj_schedule_hub_views.xml',
        'views/shahtaj_visit_hub_views.xml',
        'views/shahtaj_order_booker_users_views.xml',
        'wizard/shahtaj_generate_tasks_views.xml',
        'wizard/shahtaj_create_order_booker_views.xml',
        'views/shahtaj_product_views.xml',
        'views/shahtaj_sale_stock_fix.xml',
        'wizard/shahtaj_quick_add_product_views.xml',
        'wizard/shahtaj_add_stock_views.xml',
        'views/shahtaj_product_inventory_views.xml',
        'views/shahtaj_menus.xml',
        'views/shahtaj_api_test_menu.xml',
    ],
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}
