# -*- coding: utf-8 -*-
{
    'name': 'Shahtaj Order Booker',
    'version': '18.0.1.0.20',
    'category': 'Sales',
    'summary': 'Field order booking with routes, visits, GPS, and targets',
    'depends': ['base', 'contacts', 'sale', 'mail', 'account'],
    'data': [
        'security/shahtaj_security.xml',
        'security/ir.model.access.csv',
        'security/shahtaj_partner_access_fix.xml',
        'security/shahtaj_partner_access.xml',
        'security/shahtaj_record_rules.xml',
        'security/shahtaj_record_rules_fix.xml',
        'data/shahtaj_account_data.xml',
        'data/shahtaj_cron.xml',
        'views/shahtaj_route_views.xml',
        'views/shahtaj_zone_views.xml',
        'views/shahtaj_partner_views.xml',
        'views/shahtaj_schedule_views.xml',
        'views/shahtaj_visit_task_views.xml',
        'views/shahtaj_visit_views.xml',
        'wizard/shahtaj_visit_checkin_views.xml',
        'views/shahtaj_target_views.xml',
        'views/shahtaj_schedule_hub_views.xml',
        'views/shahtaj_visit_hub_views.xml',
        'views/shahtaj_order_booker_users_views.xml',
        'wizard/shahtaj_generate_tasks_views.xml',
        'wizard/shahtaj_create_order_booker_views.xml',
        'views/shahtaj_menus.xml',
    ],
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}
